spring.application.name=Beetle
# Configuración PostgreSQL
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/beetle_db
spring.datasource.username=beetle_user
spring.datasource.password=beetle_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para evitar problemas de timezone
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Logs para debug
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE